#spring.datasource.druid.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.druid.password=123456
#spring.datasource.druid.url=jdbc:mysql://localhost:3306/sakila
#spring.datasource.druid.username=root

book.name=WWW
book.author=QQQ



rand.aaa=${random.value}

rand.bbb=${random.int}

rand.ccc=${random.int(10)}

rand.ddd=${random.int[10,20]}